run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - typecheck
    - govet
    - staticcheck
    - ineffassign
    - deadcode
    - revive
    - stylecheck
    - unconvert
    - goconst
    - goimports
    - exportloopref
    - gocritic
