run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - maligned
    - interfacer
    - scopelint
    - gomoddirectives
    - nolintlint
    - exhaustivestruct
    - wrapcheck
    - varnamelen
    - golint
    - paralleltest
    - exhaustruct
    - wsl